In [1]:
import pandas as pd
import numpy as np

In [24]:
df = pd.read_csv('students_dataset.csv', engine='python', on_bad_lines='skip')

In [4]:
df.head()

,student_id,first_name,last_name,address,class_studying,department_hod,date_of_birth,class_ending_day,class_ending_month,class_ending_year
0,1,John,Doe,12 Main St,10A,Dr. Smith,2005-01-12,5,01,2024
1,2,Alice,Green,45 Oak Rd,10A,Dr. Smith,2005-03-22,12,01,2024
2,3,Raj,Kumar,NaN,10B,NaN,03/15/2005,18,January,2025
3,4,NaN,Lopez,@@@,10B,Dr. Gomez,15-03-2005,22,1,2025
4,5,Sam,NaN,No Address,10C,Dr. White,NaN,27,02,2024

In [5]:
df.tail()

,student_id,first_name,last_name,address,class_studying,department_hod,date_of_birth,class_ending_day,class_ending_month,class_ending_year
141,146,NaN,Singh,No Addr,7C,Dr. Patel,09-08-2005,14,08,2024
142,147,Max,Fisher,NaN,7C,Dr. Patel,2005/08/09,19,8,2024
143,148,Abc,Def,Garbage,6A,NaN,08/2005,23,8,2026
144,149,Isla,Moore,88 South St,6A,Dr. Green,2005-09-01,28,09,2026
145,150,Evan,Hall,NaN,6B,HOD MATH,01 Sep 2005,4,9,2024

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 52 entries, 0 to 144
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   student_id          52 non-null     int64
 1   first_name          52 non-null     object
 2   last_name           52 non-null     object
 3   address             52 non-null     object
 4   class_studying      52 non-null     object
 5   department_hod      52 non-null     object
 6   date_of_birth       52 non-null     object
 7   class_ending_day    52 non-null     int64
 8   class_ending_month  52 non-null     object
 9   class_ending_year   52 non-null     int64
dtypes: int64(3), object(7)
memory usage: 4.5+ KB

In [7]:
df.describe()

       student_id  class_ending_day  class_ending_year
count  146.000000        146.000000         146.000000
mean    75.376712         14.986301        2024.732877
std     43.403026          7.985320           1.071841
min      1.000000          2.000000        2023.000000
25%     38.250000          8.000000        2024.000000
50%     75.500000         15.000000        2025.000000
75%    112.750000         21.750000        2026.000000
max    150.000000         30.000000        2027.000000

In [28]:
df.isnull().sum()

student_id            0
first_name            0
last_name             0
address               0
class_studying        0
department_hod        0
date_of_birth         0
class_ending_day      0
class_ending_month    0
class_ending_year     0
dtype: int64

In [27]:
df.dropna(inplace=True)