In [19]:
import sqlite3
import csv

conn = sqlite3.connect("sales.db")
cursor = conn.cursor()

with open("../csv files/sales.csv", "r") as file:
    dr = csv.DictReader(file)
    columns = dr.fieldnames

    # create table dynamically
    cursor.execute(f"CREATE TABLE IF NOT EXISTS sales_table ({','.join(columns)})")

    for row in dr:
        cursor.execute(
            f"INSERT INTO sales_table VALUES ({','.join(['?']*len(columns))})",
            list(row.values())
        )

conn.commit()

In [17]:
import pandas as pd

In [20]:
df=pd.read_sql('select * from sales_table', conn)

In [21]:
df.head()

,order_id,order_date,customer_id,category,product,quantity,price,total_amount,city
0,1,2025-03-13,CUST_2679,Electronics,Laptop,3,497.33,1491.99,Seattle
1,2,2025-04-22,CUST_4811,Electronics,Tablet,1,69.30,69.30,Phoenix
2,3,2025-08-18,CUST_5557,Electronics,Phone,5,844.84,4224.20,Boston
3,4,2025-03-21,CUST_4527,Electronics,Phone,4,687.10,2748.40,Boston
4,5,2025-07-03,CUST_6635,Home,Chair,1,766.06,766.06,Phoenix

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      600 non-null    int64
 1   order_date    600 non-null    object
 2   customer_id   600 non-null    object
 3   category      600 non-null    object
 4   product       600 non-null    object
 5   quantity      600 non-null    int64
 6   price         600 non-null    float64
 7   total_amount  600 non-null    float64
 8   city          600 non-null    object
dtypes: float64(2), int64(2), object(5)
memory usage: 42.3+ KB

In [23]:
df.describe(include='all')

,order_id,order_date,customer_id,category,product,quantity,price,total_amount,city
count,600.000000,600,600,600,600,600.000000,600.000000,600.000000,600
unique,NaN,142,198,4,16,NaN,NaN,NaN,7
top,NaN,2025-11-30,CUST_4770,Electronics,Jacket,NaN,NaN,NaN,Houston
freq,NaN,15,6,177,54,NaN,NaN,NaN,99
mean,100.500000,NaN,NaN,NaN,NaN,2.940000,1049.706850,3013.274750,NaN
std,57.782477,NaN,NaN,NaN,NaN,1.469694,551.559452,2270.425277,NaN
min,1.000000,NaN,NaN,NaN,NaN,1.000000,21.730000,67.450000,NaN
25%,50.750000,NaN,NaN,NaN,NaN,2.000000,617.072500,1193.605000,NaN
50%,100.500000,NaN,NaN,NaN,NaN,3.000000,1088.745000,2566.370000,NaN
75%,150.250000,NaN,NaN,NaN,NaN,4.000000,1498.277500,4315.755000,NaN
max,200.000000,NaN,NaN,NaN,NaN,5.000000,1987.900000,9537.300000,NaN

In [24]:
conn.close()